name: Build GamesInTown

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
  